# -*- mode: ruby -*-
# vi: set ft=ruby :

def system_home
  ENV.fetch("HOME").tr("\\","/")
end

Vagrant.configure("2") do |config|
  config.vm.box = "minor"
  config.vm.box_check_update = false

  [1080, 3000, 3333, 4000].each do |port|
    config.vm.network "forwarded_port", guest: port, host: port, auto_correct: true, protocol: :tcp
  end

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false # true # don't need gui for terminal 
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize [ "setextradata", "global", "GUI/SuppressMessages", "all"]
  end
  
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
