#!/usr/bin/env rake
# iso source http://releases.ubuntu.com/
# http://cdimage.ubuntu.com/
boxes = %w(min minor major max maximum xubuntu)

SRC_REGEX = %r(src/(\w*)\.json)
src_files = FileList['src/*.json']
names = []
src_files.each do |src_file|
  m = SRC_REGEX.match(src_file)
  next unless m
  name = m[1]
  names.push name
  box_file = "#{name}.virtualbox.box"
  out_dir = "out/#{name}"
  ovf_file = "#{out_dir}/#{name}.ovf"
  
  namespace name do 
    file ovf_file => [src_file] do
      rm_rf out_dir
      sh "packer build -var 'name=#{name}' #{src_file}"
    end
    file box_file => ovf_file

    desc "Build the #{name} box"
    task build: ovf_file

    desc "uninstall the #{name} box"
    task :uninstall do
      sh "vagrant box remove #{name} -f || true"
    end
    
    desc "install the #{name} box"
    task install: box_file do
      sh "vagrant box add --force --name=#{name} #{box_file}"
    end

    desc "test the #{name} box"
    task test: "#{name}:install" do
      test_dir = "test/#{name}"
      rm_rf test_dir
      mkdir_p test_dir
      cd test_dir
      sh "vagrant init #{name}"
      sh "vagrant up"
      sh "vagrant ssh"
      sh "vagrant halt"
      sh "vagrant destroy -f"
      cd '../..'
      rm_rf test_dir
    end

    desc "remove the #{name} box"
    task :clean do
      rm_rf FileList["#{name}.virtualbox.box"]
      rm_rf FileList["out/#{name}"]
    end

  end

  task name => "#{name}:build"
  task build: "#{name}:build"
  task install: "#{name}:install"
  task uninstall: "#{name}:uninstall"
end

desc "install all the boxes"
task :install

desc "uninstall all the boxes"
task :uninstall

#  sh "vagrant box add --force --name=test/minor ./minor.virtualbox.box"

# file 'xenial.virtualbox.box' => 'out/min/min.ovf'

#  sh "vagrant box add --force --name=test/minor ./minor.virtualbox.box"
#  sh "cd major; vagrant destroy -f; vagrant up"

task default: :build

task :clean do
  rm_rf FileList['*.box']
  rm_rf FileList['out/*']
end

