#!/usr/bin/env ruby
# 
# this script takes a list of packages and downloads them into a file structure
# where they would be ready to install
#
# to download individual packages
# apt-get download ruby
# 
# Debootstrap is a debian utility to bootstrap an installation
# It has a handy ability to also download packages with all their dependencies 
# 
# debootstrap - Installing Debian GNU/Linux from a Unix/Linux System
# article https://www.debian.org/releases/stable/i386/apds03.html
# homepage https://wiki.debian.org/Debootstrap
# manpage https://manpages.debian.org/stretch/debootstrap/debootstrap.8.en.html
# also    https://linux.die.net/man/8/debootstrap
# 


# prepare the list of packages
packages = []
open 'packages.list' do |file|
  file.each_line do |line|
    line.chomp!
    line.sub! /\#.*$/,''
    line.strip!
    if line =~ /^[\w-]*$/
      packages.push line
    end
  end
end

# set the arguments
packages = packages.join(',')
components = "main,restricted,universe,multiverse"
release_suite = 'xenial'
target_directory = 'download'
archive_mirror = 'http://us.archive.ubuntu.com/ubuntu'

# execute debootstrap
# download-only so it does not unpack them all
exec <<~CMD.gsub(/\n\s*/,' ')
  sudo debootstrap
    --download-only
    --components="#{components}"
    --include="#{packages}"
    #{release_suite}
    #{target_directory}
    #{archive_mirror}
CMD

