#!/bin/sh -eux

if [ $# -gt 0 ] && [ -z $1 ]
then 
  passwd=$1
else
  passwd=$USER
fi

sudo_file="99_$USER"
echo "$USER ALL=(ALL) NOPASSWD:ALL" > $sudo_file
chmod 440 $sudo_file

if [ -z $passwd ]
then
  echo $passwd | sudo -S cp $sudo_file /etc/sudoers.d
else
  # the user should be prompted for the password
  sudo cp $sudo_file /etc/sudoers.d
fi

rm $sudo_file

sudo sed -i -e '/Defaults\s\+env_reset/a Defaults\texempt_group=sudo' /etc/sudoers;

