#!/bin/sh -eux
# https://help.ubuntu.com/community/AutoLogin

sudo mkdir -p /etc/lightdm/lightdm.conf.d
sudo tee /etc/lightdm/lightdm.conf.d/50-myconfig.conf <<AUTOLOGIN
[SeatDefaults]
autologin-user=$USER
AUTOLOGIN

