#!/bin/sh -eux

sudo sed -i -e '/Defaults\s\+env_reset/a Defaults\texempt_group=sudo' /etc/sudoers;

# Set up password-less sudo for the vagrant user
file="/etc/sudoers.d/99_$USER"
sudo tee $file <<-NOPASSWD
$USER ALL=(ALL) NOPASSWD:ALL
NOPASSWD

sudo chmod 440 $file

