#!/bin/sh -eux

sudo apt-get install -y --no-install-recommends \
  qt5-default libqt5webkit5-dev \
  gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x \
  firefox xvfb

gem install capybara-webkit

