#!/bin/bash -eux
## this one needs bash.. sh won't work.

# setup gems to not install documentation
touch ~/.gemrc
if ! grep -q 'gem: --no-document' ~/.gemrc
then
  echo "gem: --no-document" >> ~/.gemrc
fi

# update apt data
sudo apt-get -y update

# install prerequisites
sudo apt-get -y install software-properties-common gnupg2 build-essential ca-certificates

# install rvm key
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

## install rvm ruby and default gems
curl -sSL https://get.rvm.io | bash -s stable --ruby --with-default-gems="bundler rails sass"

# load rvm as a function  # sh does not have source
source ~/.rvm/scripts/rvm

# install ruby 2.5.0
rvm install 2.5.0
rvm use 2.4.3
gem update --system

# install and Use Ruby 2.4.3 as default
rvm install 2.4.3
rvm use --default 2.4.3
gem update --system

