#!/bin/bash

sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get -y update

## Accept the license 
sudo /usr/bin/debconf-set-selections <<-ACCEPT
oracle-java8-installer shared/accepted-oracle-license-v1-1 select true
ACCEPT

sudo apt-get -y install oracle-java8-installer
sudo apt-get -y install oracle-java8-set-default

