#!/bin/sh -eux

# Use the latest version of Git.  
# The following will add the PPA and install:

sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git

# standard aliases 
git config --global alias.logg 'log --oneline --graph --decorate'
git config --global alias.sync '!git fetch origin && git remote prune origin && :'
git config --global alias.reebase-master '!git fetch origin master:master && git rebase master'

