#!/bin/bash -eux

sudo apt-get -y install \
  vim vim-gnome vim-pathogen vim-addon-manager vim-airline vim-airline-themes \
  vim-rails vim-fugitive vim-lastplace vim-latexsuite vim-command-t vim-conque \
  vim-ctrlp vim-doc vim-editorconfig vim-gocomplete vim-python-jedi vim-scripts \
  vim-snipmate vim-snippets vim-syntastic vim-syntax-docker vim-tabular vim-tlib \
  vim-ultisnips vim-vimoutliner vim-voom vim-youcompleteme tidy ispell

git clone https://github.com/capnregex/vim_dotfiles.git ~/.vim
git clone git@github.com:capnregex/vim_dotfiles.git ~/.vim
              

cp ~/.vim/.vimrc ~/
cp ~/.vim/.gvimrc ~/

