#!/bin/sh -eux

sudo apt-get -y update

# install prerequisites
sudo apt-get -y install software-properties-common gnupg2 build-essential ca-certificates

# install rvm key
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

curl -sSL https://get.rvm.io | bash -s stable --ruby --with-default-gems="bundler rails sass"

. ~/.rvm/scripts/rvm

bash -l -c -- rvm install ruby
bash -l -c -- rvm install 2.5.0

