#!/bin/sh -eux

sudo apt-get -y update
sudo apt-get -y install apt-transport-https
## Add yarn repo
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get -y update
sudo apt-get -y install npm yarn

# this command will direct npm to use the ca cert pem bundle homebrew created when 
# it installed openssl
# npm config set cafile="`ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE'`"
# npm config set "strict-ssl" true

sudo npm install -g n

sudo n latest

