#!/bin/sh -eux

key="https://dl-ssl.google.com/linux/linux_signing_key.pub"
list="/etc/apt/sources.list.d/google-earth-pro.list"
repo="http://dl.google.com/linux/earth/deb/"

wget -q -O - $key | sudo apt-key add - 

sudo tee $list <<CFG 
deb [arch=amd64] $repo stable main
CFG

sudo apt-get -y update
sudo apt-get -y install google-earth-pro

