#!/bin/sh -eux

## refresh apt-cache 
sudo apt-get -y update

## make sure we are up to date with our patches
sudo apt-get -y upgrade

## install core packages
sudo apt-get -y install \
  linux-virtual xubuntu-core openssh-server \
  build-essential ruby nodejs npm firefox wget curl \
  vim-gnome terminator


