#!/bin/sh -eux
# install docker-ce
## https://docs.docker.com/install/linux/docker-ce/ubuntu/

# update apt
sudo apt-get -y update

# remove older versions of docker
sudo apt-get -y remove docker docker-engine docker.io

# install prerequisites
sudo apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

# add dockers key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# verify key
sudo apt-key fingerprint 0EBFCD88

# add docker repository
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get -y update

# install-docker-ce-1
sudo apt-get -y install docker-ce

# verify install
sudo docker run hello-world

## manage-docker-as-a-non-root-user
## https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
sudo groupadd docker

sudo usermod -aG docker $USER

# docker installed, you may need to reboot for permissions to update
# verify that docker can run as $USER
# $ docker run hello-world

